version: '3.9'

services:
  db:
    container_name: mongo
    image: mongo:6.0
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db

  app:
    container_name: zurich_app
    image: frontend_rightnow_migracion_app:latest
    ports:
      - 3000:3000
    environment:
      - MONGODB_URI=mongodb://db:27017/117mdr
    volumes:
      - ./assets:/app/assets
    depends_on:
      - db
    command: npm run seed
